name: UMC Dev CI/CD

on:
  pull_request:
    types: [ closed ]
  workflow_dispatch:
  # (2). 수동 실행이 가능하도록

jobs:
  build:
    runs-on: ubuntu-latest  # (3). OS 환경
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

    #Github Action을 통해 깃허브가 자체적으로 리눅스 가상 환경을 만들어서 배포 및 빌드 과정 진행
    - name: Generate deployment package
      run:
        mkdir -p deploy
        cp build/libs/*.jar deploy/applicaiton.jar
        cp Procfile deploy/Procfile
        cp -r .ebextensions-dev deploy/.ebextensions
        cp -r .platform-dev deploy/.platform
        cd deploy && zip -r deploy.zip .

